### ISSUE TITLE
Crashes FFXIV when going into GPOSE

### ISSUE THREAD

**Issue by AimmePuff** [imchillin/CMTool#112]
Hey I'm hoping someone can help me out - I'm not the brightest crayon in the pack when it comes to anything related to PC knowledge :') When I go into gpose in FFXIV and try to use CMTOOLS it crashes my game instantly with this error message (have attached pic) I have no idea what the issue is and was really hoping someone could maybe help me out? 
![IMG_4501](https://user-images.githubusercontent.com/112999020/188779617-25a4c2c2-4b0f-4cfd-bf0f-6d873d90f51d.JPG)

**Comment by Badglory** [comment]
Cmt has been abandoned by its creators so I hope someone who understands how to edit it will get it working again.

**Comment by Jenixa** [comment]
Its because you can now use CMP poses on Anamesis.

**Comment by AimmePuff** [comment]
Ive given up on cmtools now haha - Just started using Anamnesis ୧( “̮ )୨
