### ISSUE TITLE
Auto-refresh and/or hotkey to manually refresh

### ISSUE THREAD

**Issue by KarlitosVII** [imchillin/CMTool#41]
Hello,
It would be great to add an option to auto-refresh selected actor when traveling to an other zone and/or add an option to use an hotkey to manually refresh.

I have an issue right now with unique head type like Ysayle (Elezen Wilwood Head Type 202) which need a refresh each time I travel to an other zone or in cutscenes because the game revert the head with a default one. I suppose this a limitation of CMTool.

**Comment by enalagrange** [comment]
Took a short look at a way to auto refresh, unfortunately doesn't seem to be possible with the current architecture due to the zone information loading in before character information is, so the re-rendering timing is off.

**Comment by Ani-ki** [comment]
Given the current architecture this is not possible. It will be implemented in Anamnesis, however.
