### ISSUE TITLE
Other players/NPCs randomly turning into my character when CMTool is open

### ISSUE THREAD

**Issue by thatguywithawatch** [imchillin/CMTool#51]
Ever since the 5.3 update, if I'm playing while CMTool is open, nearby players or NPCs will occasionally take on my exact appearance and outfit. I never turn Target Mode on, and it's usually someone I haven't even targeted at any point.

**Comment by Bluefissure** [comment]
This can happen at any time or only after you click character refresh?

**Comment by thatguywithawatch** [comment]
I *think* it's only happened if I've recently hit character refresh. Just played for an hour without touching CMTool (but with it open) and it and it hasn't happened again so far.

**Comment by Ani-ki** [comment]
Issue resolved in earlier patch.
