### ISSUE TITLE
game crashes every time I use the posing matrix while in GPose

### ISSUE THREAD

**Issue by ANorth023** [imchillin/CMTool#60]
Not sure how to fix this issue..... I've tried different poses... and my game with just crash every time it tried to implement this...Not sure.... what to do. The game is using text tools just fine..... but every time I try and change things with CMtool it-just crashes my game :c

**Comment by Ani-ki** [comment]
This is due to mismatched offsets, which happens after every patch. The offsets have just been updated; please wait for the update to come through.
