### ISSUE TITLE
Microsoft Defender falsely flags latest version (v2.0.9.21) as a Trojan

### ISSUE THREAD

**Issue by mrburrito** [imchillin/CMTool#66]
The auto-updater for some reason didn't update to the latest version and, when trying to download and install v2.0.9.21 from both GitHub and when emailed the tool, Windows Defender flags it as having the Trojan `Wacatac.B!ml`. Running some supplemental scans to verify this is a false positive. Not sure if you're able to sign the code (or are already) as that may help avoid triggering Defender in the future.
![warning](https://user-images.githubusercontent.com/1143629/101994892-0d3f2300-3c94-11eb-8240-3453a8f0289b.jpg)

**Comment by Bluefissure** [comment]
I download from github release and it didn't trigger my Windows Defender.
And it seems ur downloading from filebin.net.

**Comment by mrburrito** [comment]
Most everything I saw pointed to false positive and a secondary scanning tool that uses the same definitions didn’t flag it. 99.9% sure it’s a false positive and I have no clue exactly what conditions trigger it. Only mitigation I saw on dev end was a recommendation to sign the code, but even that wasn’t fully effective.
