### ISSUE TITLE
Discord link invalid + Equipment Sorting doesn't work + Animations disabled

### ISSUE THREAD

**Issue by Wephrf** [imchillin/CMTool#68]
**► Discord link invalid**
The invitation link is invalid everywhere, aka the addon itself and GitHub. I had to dig to find it

**► Equipment Sorting doesn't work**
When selecting a job, or a discipline of (x) etc, it doesn't do anything. It only works for weapons.
This was already the case in the previous version.

**► Animation disabled**
![image](https://user-images.githubusercontent.com/76115019/102365511-ec3e4100-3fb7-11eb-9906-43754e86b451.png)

**Edit : animations and sorting are apparently known issues, but this I could only find out after digging hard to find the discord server. So the discord thing remains an issue**

**Comment by Bluefissure** [comment]
Discord Link: https://discord.com/invite/crystallinemeans
Animation is not functioning since patch 5.4 and developers are invesgating it.
