### ISSUE TITLE
Game crashes on loading a cm pose

### ISSUE THREAD

**Issue by gibbles2244** [imchillin/CMTool#71]
any time I boot cm it boots fine, but when I load a pose while under gpose and with everything frozen it simply closes the entire ffxiv game instantly. If I use the old or current posing matrix, regardless it simply closes my game out instantly, with any pose I try.

**Comment by Bluefissure** [comment]
Which server do you play in and what's the version of CMTool you use?

**Comment by gibbles2244** [comment]
I play on Aether, Jenova. And my version is v2.0.9.21

**Comment by gibbles2244** [comment]
I should mention all other functionality is intact. it simply crashes my game when i load a custom pose either made by myself or downloaded

**Comment by Bluefissure** [comment]
Could you try the [latest release](https://github.com/imchillin/CMTool/releases/latest)?

**Comment by gibbles2244** [comment]
ah that was my problem. thanks. i tried using the updated earlier but nothing happened, my bad
