### ISSUE TITLE
CMtool in wrong folder / anti virus blocking CMtool

### ISSUE THREAD

**Issue by AkariCartel** [imchillin/CMTool#72]
Hi! I have been getting this error and have tried everything in my power to get CMtool to work. I wasn't getting this error yesterday and I haven't touched CMtool all day today. I have allowed it through my Anti Virus and have tried reinstalling it and moving it in different folders to see if it'll work with no solution so far. I'm not sure if this is an issue with the tool itself or if I'm doing something wrong. 

![cmtoolhelp](https://user-images.githubusercontent.com/77904249/105617392-b3ea0980-5d92-11eb-96b9-6eee122f0f61.png)

**Comment by MistressAshai** [comment]
Getting the same error, but the exception is different.

![image](https://user-images.githubusercontent.com/8222603/115011219-3d294d80-9e63-11eb-8d7e-9248df8492f2.png)
