### ISSUE TITLE
AV Flagging

### ISSUE THREAD

**Issue by Sweetkitten88** [imchillin/CMTool#79]
Yes ever since this new update my avast is flagging the cmtool as a Filerepmalware even tho i dont have it in any folder or desktop that would cuase this issue this is what im getting before my AV puts t he  exe file into the virus chest i didn't have this issue before this new update i do hope you guys can get this fixed and such mean i have made it an Expection in my Avast AV but its just odd i have to now when i didn before

![image](https://user-images.githubusercontent.com/84615039/119217246-89892e00-ba9e-11eb-9880-56a3219505cb.png)

**Comment by LeonBlade** [comment]
False positives will continue to happen, if you whitelist the folder that CMT is in, you shouldn't have this issue going forward.
