### ISSUE TITLE
not functioning

### ISSUE THREAD

**Issue by fracturedhourglass** [imchillin/CMTool#80]
program will not open or run, despite exceptions made to antivirus/defender. 

crashed in about 15 different ways with 15 different popups. This has literally been broken since the korean update. So many error messages I can't even copy them all.

**Comment by vallana** [comment]
Got the same problem. Got error messages that the environment option couldn't load properly so I thought reinstalling would fix it but now the program doesn't open at all.

**Comment by bashed0** [comment]
its because of the trojan in the new update. Its name is programm:win32/uwamson.a!ml

**Comment by rblanker** [comment]
It is blocked by Windows like basked0 reported. Use the previous version. Hope this will get fixed too and it was hopefully a false positive.

**Comment by LeonBlade** [comment]
Latest build should fix the issue. It was a false positive, I already reported on it.
