### ISSUE TITLE
Alarming detection by Kaspersky/ Win Defender

### ISSUE THREAD

**Issue by bashed0** [imchillin/CMTool#81]
There comes the Trojan 'programm:win32/uwamson.a!ml' with the new update

**Comment by rblanker** [comment]
Detection by 10 virus vendors (this might be false positives). Only defender seems to detect Program:Win32/Uwamson.A!ml

Scanned using the version in the release zip Concept Matrix 2.0.14.3
https://www.virustotal.com/gui/file/437b36fa22e0fc3d2b6d6cc03a5e8fe85b600e5c0d9e0180c953709d873b20fa/detection

The previous version had 3 detections, so remember these can be false positives, but 10 is something that needs to be investigated.

The korean update stopped working after the first automatic update for me too. I am using previous version, which works fine. I got Windows 10 UK build 19041.985. Windows defender has blocked the program locally. It rate it as a low treat.

**Comment by bashed0** [comment]
In my case it was Kaspersky. If you search for Program: Win32 / Uwamson.A! Ml, you will also find various reports about it on Google. As a precaution, I first titled it as a Trojan so that the creator would react to the post and explain the file. It is better to be careful right from the start

**Comment by LeonBlade** [comment]
Latest build fixes it. It was just a false positive. This latest build changes nothing about the codebase except for one thing (the assembly version) and yet the results of the scan has changed.

https://www.virustotal.com/gui/file/6e041388ce2bc913640492ddc82b29f93d054d2c747e2998feaff10ba4c35d83/detection
