### ISSUE TITLE
Haukke Manor (Hard) Halicarnassus?

### ISSUE THREAD

**Issue by coldReactive** [imchillin/CMTool#86]
Is there a way to use the Halicarnassus model from Haukke Manor (Hard)?

**Comment by LeonBlade** [comment]
This isn't an issue.

**Comment by LeonBlade** [comment]
If you go to the equipment section, there is a way to load in NPC equipment, you might be able to find the model in there, otherwise you have to go to the model list and search for her there.

**Comment by coldReactive** [comment]
> 
> 
> If you go to the equipment section, there is a way to load in NPC equipment, you might be able to find the model in there, otherwise you have to go to the model list and search for her there.

Unfortunately she isn't there, just, the Omega versions:
![ry5sCkK](https://user-images.githubusercontent.com/1313673/133428608-f9daef7e-632c-4ea9-80a5-b3ba77f867c7.jpg)
![78HKQql](https://user-images.githubusercontent.com/1313673/133428620-3ac6ac63-f59f-49c6-b686-7ad075beb140.jpg)

**Comment by coldReactive** [comment]
In addition, the Shadowcourt Handmaiden, which used to be in Dun Scaith isn't in the model or equipment list, which also used a different model.
