### ISSUE TITLE
CMTool Closes upon launching.

### ISSUE THREAD

**Issue by Detriyari** [imchillin/CMTool#90]
When opening CMTool, met with the following:

"The image data generated an overflow during processing"

And then it closes automatically afterwards. Doesn't boot up, nothing. Just completely crashes. And every time I open it, it's the same. I don't know how to fix it.

**Comment by jigibbs93** [comment]
Similar issue, im met with a string of error messages starting with one that reads "object reference not  set to an instance of an object
